spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:postgresql://localhost:5432/cartas_yugioh
    data-username: sa
    data-password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

importador-cartas:
  url: http://localhost:8081/importacao