spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yugiohdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging.level:
  org:
    hibernate:
      SQL: TRACE
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
    springframework:
      web: DEBUG
      data: debug

feign:
  client:
    config:
      default:
        #connectTimeout: 5000
        #readTimeout: 5000
        loggerLevel: full
